name: 'Generate Dependency Data File'
description: 'Generates a tab delimined file that contains a list of the depenencies detected in the specified repo.'
branding:
  icon: 'package'
  color: 'green'
inputs: 
  repo-token:
    description: 'REQUIRED: The GITHUB_TOKEN secret. Make sure this token has rights to all the repos you want to catalog.'
    required: true
  org-name:
    description: 'The name of the owner/organization that contains the repositories (defaults to current repository owner)'
    default: ${{ github.repository_owner }}
    required: true
  repo-names:
    description: 'REQUIRED: A comma separated list of repository names to catalog.'
    required: true
  depth:
    description: "The depth of transitive dependencies to report on.  Defaults to 0,  which will not include transitives (i.e. it will only list packages from manifests found in the repo).  Higher numbers will include transitive dependencies by including the manifests from the included packages' repos as well, but can significantly increase scan time."
    required: true
    default: "0"

runs:
  using: 'node20'
  main: 'dist/index.js'
