name: Action test

on:
  workflow_dispatch:
    inputs:
      repo-names:
        description: "Comma separated list of repos to scan."
        required: true
        default: "f1tv-dl"
      depth:
        description: "The depth of transitive dependencies to report on."
        required: true
        default: "0"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Genereate a list of dependencies for this repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate dependencies action
        uses: ./ # Uses an action in the root directory
        with:
          repo-token: ${{ secrets.DEPS_TOKEN_INTERNAL }}
          repo-names: ${{ github.event.inputs.repo-names }}
          depth: ${{ github.event.inputs.depth }}
