name: Action test

on:
  workflow_dispatch:
    inputs:
      depth:
        description: "The depth of transitive dependencies to report on."
        required: true
        default: "0"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Genereate a list of dependencies for this repository
    permissions:
      contents: read
      actions: read
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate dependencies action
        uses: ./ # Uses an action in the root directory
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-names: 'generate-dependencies-csv-action'
          org-name: 'thedave42'
          depth: ${{ github.event.inputs.depth }}
